# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      %kernel.root_dir%/../web
    filters:
        lessphp:
            file:       %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to:   "\.less$"
            presets:
                fa-font-path: "'/duplo'"
        cssrewrite: ~
        cssembed:
            jar:        %kernel.root_dir%/../vendor/packagist/cssembed-bin/bin/cssembed.jar
            apply_to:   "\.css$"
        yui_css:
            jar:        %kernel.root_dir%/../vendor/packagist/yuicompressor-bin/bin/yuicompressor.jar
            apply_to:   "\.css$"
        yui_js:
            jar:        %kernel.root_dir%/../vendor/packagist/yuicompressor-bin/bin/yuicompressor.jar
    assets:
#        # Bootstrap
#        Bootstrap-halflings:
#            inputs:
#                -       %kernel.root_dir%/../vendor/twbs/bootstrap/img/glyphicons-halflings.png
#            output:     'img/glyphicons-halflings.png'
#        Bootstrap-halflings-white:
#            inputs:
#                -       %kernel.root_dir%/../vendor/twbs/bootstrap/img/glyphicons-halflings-white.png
#            output:     'img/glyphicons-halflings-white.png'
        # FontAwesome
        FontAwesome-eot:
            inputs:
                -       %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.eot
            output:     'font/fontawesome-webfont.eot'
        FontAwesome-svg:
            inputs:
                -       %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.svg
            output:     'font/fontawesome-webfont.svg'
        FontAwesome-ttf:
            inputs:
                -       %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.ttf
            output:     'font/fontawesome-webfont.ttf'
        FontAwesome-woff:
            inputs:
                -       %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.woff
            output:     'font/fontawesome-webfont.woff'
